-- cria tabela marca
create table marca(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	nome_marca VARCHAR(50) NOT NULL
);

-- cria tabela modelo
create table modelo(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
	id_marca BIGINT NOT NULL,
	nome varchar(70) NOT NULL unique
);
ALTER TABLE modelo ADD CONSTRAINT fk_modelo_marca FOREIGN KEY (id_marca) references marca;


-- cria tabela carro
create table carro(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
	timestamp_cadastro TIMESTAMP not null,
	modelo_id BIGINT not null,
	ano CHAR(4) not null,
	combustivel VARCHAR(30) not null,
	num_portas INTEGER NOT NULL,
	cor VARCHAR(30) NOT NULL
);
ALTER TABLE carro ADD CONSTRAINT fk_carro_modelo FOREIGN KEY (modelo_id) REFERENCES modelo;